= Step by step guide for installing enonic XP as windows service


== 1. Java

Enonic XP SDK version comes with bundled Java. If you have some other version that doesn't include Java then you'll have to install it manually. Check if there's `jdk` folder in your XP installation if you are not sure.

== 2. Download Windows service wrapper

Download windows service wrapper binary from https://github.com/kohsuke/winsw[this repo] and rename the downloaded file to desired name, i.e `winsw-2.2.0-bin.exe` -> `xp-service.exe`

== 3. Create windows service wrapper config

Create new xml file named `xp-service.xml` _next to the_ `xp-service.exe` file.

NOTE: xml file should be named exactly the same as exe in order for the service to discover it

=== 4. Edit the config file

Refer to the https://github.com/kohsuke/winsw/blob/master/doc/xmlConfigFile.md[config description] to see all available options.

`%BASE%` variable always points to the config file location

[source, xml]
----
<service>
    <id>xp-service</id>
    <name>Enonic XP Service</name>
    <description>Enonic XP distribution run as a MS Windows service.</description>
    <env name="XP_INSTALL" value="%BASE%/enonic-xp-windows-sdk-7.0.0"/>    // <1>
    <env name="JAVA_HOME" value="%XP_INSTALL%/jdk"/>                           // <2>
    <env name="XP_HOME" value="%BASE%/xp-service-home"/>                       // <3>
    <executable>%XP_INSTALL%/bin/server.bat</executable>
    <log mode="roll-by-size-time">                                             // <4>
        <sizeThreshold>10240</sizeThreshold>
        <pattern>dd-MM-yyyy</pattern>
        <autoRollAtTime>00:00:00</autoRollAtTime>
        <keepFiles>7</keepFiles>
    </log>
    <serviceaccount>                                                           // <5>
        <domain>***user domain***</domain>
        <user>***user name***</user>
        <password>***user password***</password>
        <allowservicelogon>true</allowservicelogon>
    </serviceaccount>
</service>
----

<1> location of you enonic XP distribution (next to config file in `enonic-xp-windows-sdk-7.0.0` folder)
<2> No need to modify if you used enonic XP SDK, your java home otherwise (system-wide `JAVA_HOME` will be used if omitted)
<3> location of enonic XP home folder (next to config file in `xp-service-home` folder)
<4> rotates log using <pattern> provided by both date and file size
<5> user account (and password) that the service will run as  (`allowservicelogon` will automatically be set to true for specified user)

TIP: To know your user name and domain type `set user` in cmd and hit enter

=== 5. Using service

IMPORTANT: You need to start cmd.exe with administrator rights to run service commands

==== Installing
First, we need to install our new service.
Following command is used to do it:

 xp-service.exe install
 2019-06-20 18:09:38,107 INFO  - Installing the service with id 'xp-service'

where `xp-service.exe` is the name of the service wrapper you downloaded earlier.

==== Checking status

You can check its status now by running following command:

 xp-service.exe status
 Stopped

==== Starting

Service is stopped by default and we need to start it with the following command:

 xp-service.exe start
 2019-06-20 18:12:44,698 INFO  - Starting the service with id 'xp-service'

We should see that server is started if we check its status now:

 xp-service.exe status
 Started

==== Stopping

To stop the service type:

 xp-service.exe stop
 2019-06-20 18:17:14,588 INFO  - Stopping the service with id 'xp-service'

==== Uninstalling

To uninstall the service type:

 xp-service.exe uninstall
 2019-06-20 18:18:02,356 INFO  - Uninstalling the service with id 'xp-service'
